source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'ModelA_Example' do
  
  pod 'ModelA', :path => '../'

  target 'ModelA_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
