source 'https://github.com/CocoaPods/Specs.git'



target 'ModelA_Example' do
  use_frameworks!
  pod 'ModelA', :path => '../'

  target 'ModelA_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
